# Tensores

* Tensores são uma matriz de um número, vetores, matrizes ou matrizes n-dimensionais.

In [13]:
import torch

In [14]:
# Números
print(f"Dado: {torch.tensor(4.)}")
print(f"Tipo de dado: {torch.tensor(4.).dtype}")
# 4. é uma abreviação para 4.0

Dado: 4.0
Tipo de dado: torch.float32


In [15]:
# Vetores
print(f"Dado: {torch.tensor([1., 2, 3, 4])}")
print(f"Tipo de dado: {torch.tensor([1., 2, 3, 4]).dtype}")

Dado: tensor([1., 2., 3., 4.])
Tipo de dado: torch.float32


In [16]:
# Matriz
print(f"Dado: {torch.tensor([[1., 2, 3, 4], [5, 6, 7, 8]])}")
print(f"Tipo de dado: {torch.tensor([[1., 2, 3, 4], [5, 6, 7, 8]]).dtype}")

Dado: tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
Tipo de dado: torch.float32


In [17]:
# Matriz 3-Dimensional
print(
    f"Dado: {torch.tensor([[[1., 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])}"
)
print(
    f"Tipo de dado: {torch.tensor([[[1., 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]]).dtype}"
)

Dado: tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.],
         [13., 14., 15., 16.]]])
Tipo de dado: torch.float32


* Tensores podem ter qualquer tanto de dimensões e diferentes comprimentos. Podemos inspecionar o comprimento de cada dimensão utilizando a propriedade `.shape`

In [18]:
t1 = torch.tensor(4.0)  # Escalar
t2 = torch.tensor([1.0, 2, 3, 4])  # 1-Dimensional
t3 = torch.tensor([[1.0, 2, 3, 4], [5, 6, 7, 8]])  # 2-Dimensional
t4 = torch.tensor(
    [[[1.0, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]]
)  # 3-Dimensional

print(f"Dimensão do dado: {t1.shape}")
print(f"Dimensão do dado: {t2.shape}")
print(f"Dimensão do dado: {t3.shape}")
print(f"Dimensão do dado: {t4.shape}")

Dimensão do dado: torch.Size([])
Dimensão do dado: torch.Size([4])
Dimensão do dado: torch.Size([2, 4])
Dimensão do dado: torch.Size([2, 2, 4])


## Operações e Gradientes

* Podemos combinar tensores com algoritmos comuns de operação.

In [19]:
# Criação de tensores
x = torch.tensor(3.0)
w = torch.tensor(4.0, requires_grad=True)
b = torch.tensor(5.0, requires_grad=True)

In [20]:
# Aritmética
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

* O que torna o PyTorch unico é que pode calcular automaticamente as derivadas de `y` para os tensores que possuem gradiente requerido. Essa característica se chama Autograd.

In [21]:
# Calcula as derivadas
y.backward()
y

tensor(17., grad_fn=<AddBackward0>)

In [22]:
# Exibe os gradientes
print(f"dy/dx = {x.grad}")
print(f"dy/dw = {w.grad}")
print(f"dy/db = {b.grad}")

dy/dx = None
dy/dw = 3.0
dy/db = 1.0


* Gradiente e derivada são termos que representam a mesma coisa. O termo "gradiente" é mais comumente utilizado no contexto de matrizes e vetores

## Funções de Tensores

* Além das operações aritméticas, o PyTorch também contém muitas funções para criação e manipulação de tensores.

In [24]:
# Criando tensores com um valor fixo para todos os elementos
t1 = torch.full((3, 2), 42)
t2 = torch.full((3, 2), 55.0)
t1, t2

(tensor([[42, 42],
         [42, 42],
         [42, 42]]),
 tensor([[55., 55.],
         [55., 55.],
         [55., 55.]]))

In [25]:
# Concatenando tensores com tamanhos compatíveis
t_c = torch.cat((t1, t2))
t_c

tensor([[42., 42.],
        [42., 42.],
        [42., 42.],
        [55., 55.],
        [55., 55.],
        [55., 55.]])

In [26]:
# Calculando o cosseno de cada elemento
print(t_c.cos())

tensor([[-0.4000, -0.4000],
        [-0.4000, -0.4000],
        [-0.4000, -0.4000],
        [ 0.0221,  0.0221],
        [ 0.0221,  0.0221],
        [ 0.0221,  0.0221]])


In [27]:
# Mudando a dimensão de um tensor
print(t_c.reshape(3, 4))

tensor([[42., 42., 42., 42.],
        [42., 42., 55., 55.],
        [55., 55., 55., 55.]])


# Interoperabilidade com NumPy

In [30]:
import numpy as np

In [32]:
x = np.array([[1, 2], [3, 4.0]])
x

array([[1., 2.],
       [3., 4.]])

In [36]:
# Convertendo um array numpy para um tensor
y = torch.from_numpy(x)
print(y)

print(f"\nTipo antigo: {x.dtype}. Tipo novo: {y.dtype}")

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

Tipo antigo: float64. Tipo novo: torch.float64


In [37]:
# Convertendo um tensor para um array numpy
z = y.numpy()
print(z)

print(f"\nTipo antigo: {y.dtype}. Tipo novo: {z.dtype}")

[[1. 2.]
 [3. 4.]]

Tipo antigo: torch.float64. Tipo novo: float64


A interoperabilidade entre PyTorch e Numpy é essencial por conta da maioria dos conjuntos de dados são lidos e processados com numpy.

Poderíamos usar apenas o Numpy para o trabalho com dados numéricos multi-dimensionais, mas há alguns pontos:


1. Autograd: Conseguir computar automaticamente os gradientes é essencial para o treinamento de modelos de Deep Learning

2. GPU's: Trabalhar com conjuntos de dados grandes o bastante para se justificar o uso de redes neurais também requer hardwares específicos para o processamento em paralelo. Podemos realizar o mesmo trabalho que CPU's em minutos, em vez de horas, utilizando GPU's